version: '3'
services:
  clip-interrogator-service:
    image: clip-interrogator
    restart: always
    ports:
      - 3040:3040
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]